#ifndef __LIBBITFURY_CONFIG_H__
#define __LIBBITFURY_CONFIG_H__

#ifdef BITFURY_METABANK

#define BITFURY_MAXCHIPS 256
#define BITFURY_MAXBANKS 32
#define BITFURY_BANKCHIPS 8
#define BITFURY_SCANHASH_DELAY 60

#endif

#ifdef BITFURY_NEEDBMW_NOMUX

#define BITFURY_MAXCHIPS 100
#define BITFURY_MAXBANKS 1
#define BITFURY_BANKCHIPS 100
#define BITFURY_SCANHASH_DELAY 100

#endif

#ifdef BITFURY_QBIT

/*#define BITFURY_MAXCHIPS 180
#define BITFURY_MAXBANKS 10
#define BITFURY_BANKCHIPS 18
#define BITFURY_SCANHASH_DELAY 60*/

#define BITFURY_MAXCHIPS 36
#define BITFURY_MAXBANKS 2
#define BITFURY_BANKCHIPS 18
#define BITFURY_SCANHASH_DELAY 60

#endif

#endif